name: ZenQuest development deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  GOOGLE_ID: ${{ secrets.GOOGLE_ID }}
  GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}
  DATABASE_URL: ${{ secrets.DATABASE_URL_DEV }}
  NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET_DEV }}
  NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL_DEV }}
  OPEN_AI: ${{ secrets.OPEN_AI }}
on:
  push:
    branches:
      - development
jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: ls existing variables
        run: vercel env ls preview  --token=${{ secrets.VERCEL_TOKEN }} 
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }} 
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}  
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} 
